### ISSUE TITLE
Security vulnerability

### ISSUE THREAD

**Issue by anson-vandoren** [srobinson2018/log-collection#3]
As a user running this service, I would expect that only files inside `/var/log` would be available for someone to query. However, if I use a request like:

```shell
$ curl "localhost:8080/logs?fileName=../../etc/passwd"
```
I am able to trivially get any file on the filesystem

**Comment by srobinson2018** [comment]
Good call out! I would/should have found this in the unit testing. I added a quick regex parser to limit the characters allowed to only valid file characters and remediate the XSS vulnerability.
